### ISSUE TITLE
Population.io-api repository missing

### ISSUE THREAD

**Issue by TheRizzen** [worldpopulation/population.io-mobile#7]
Hey guys.

Not sure it is the right place for me to ask this question, but couldn't find a more appropriate place.
What happened to the repository for 'http://api.population.io' ? I'm starting using it for some projects of mine.

**Comment by mlecz** [comment]
Hello, 
Repository is no longer public. Please contact us here: hello@worlddata.io with more details about your project. Maybe we can help.
BR
Piotr

**Comment by TheRizzen** [comment]
Okay, thanks.
